name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  "build":
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      run: |
        cd clamav/ && docker build . --tag romarcablao/clamav:0.104.1
        cd ../clamav-api/ && docker build . --tag romarcablao/clamav-api:0.104.1


